package NewLanguageMTM.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptDataFlow = createDescriptorForDataFlow();
  /*package*/ final ConceptDescriptor myConceptDataFlowInstance = createDescriptorForDataFlowInstance();
  /*package*/ final ConceptDescriptor myConceptDataFlowReference = createDescriptorForDataFlowReference();
  /*package*/ final ConceptDescriptor myConceptDataStore = createDescriptorForDataStore();
  /*package*/ final ConceptDescriptor myConceptElement = createDescriptorForElement();
  /*package*/ final ConceptDescriptor myConceptElementInstance = createDescriptorForElementInstance();
  /*package*/ final ConceptDescriptor myConceptElementReference = createDescriptorForElementReference();
  /*package*/ final ConceptDescriptor myConceptExternalEntity = createDescriptorForExternalEntity();
  /*package*/ final ConceptDescriptor myConceptFlow = createDescriptorForFlow();
  /*package*/ final ConceptDescriptor myConceptFlowsRepo = createDescriptorForFlowsRepo();
  /*package*/ final ConceptDescriptor myConceptProcess = createDescriptorForProcess();
  /*package*/ final ConceptDescriptor myConceptSubProcess = createDescriptorForSubProcess();
  /*package*/ final ConceptDescriptor myConceptSubProcessFlow = createDescriptorForSubProcessFlow();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptDataFlow, myConceptDataFlowInstance, myConceptDataFlowReference, myConceptDataStore, myConceptElement, myConceptElementInstance, myConceptElementReference, myConceptExternalEntity, myConceptFlow, myConceptFlowsRepo, myConceptProcess, myConceptSubProcess, myConceptSubProcessFlow);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.DataFlow:
        return myConceptDataFlow;
      case LanguageConceptSwitch.DataFlowInstance:
        return myConceptDataFlowInstance;
      case LanguageConceptSwitch.DataFlowReference:
        return myConceptDataFlowReference;
      case LanguageConceptSwitch.DataStore:
        return myConceptDataStore;
      case LanguageConceptSwitch.Element:
        return myConceptElement;
      case LanguageConceptSwitch.ElementInstance:
        return myConceptElementInstance;
      case LanguageConceptSwitch.ElementReference:
        return myConceptElementReference;
      case LanguageConceptSwitch.ExternalEntity:
        return myConceptExternalEntity;
      case LanguageConceptSwitch.Flow:
        return myConceptFlow;
      case LanguageConceptSwitch.FlowsRepo:
        return myConceptFlowsRepo;
      case LanguageConceptSwitch.Process:
        return myConceptProcess;
      case LanguageConceptSwitch.SubProcess:
        return myConceptSubProcess;
      case LanguageConceptSwitch.SubProcessFlow:
        return myConceptSubProcessFlow;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForDataFlow() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguageMTM", "DataFlow", 0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x543ecec7f1d811f8L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:6c0627d3-4986-4ace-b681-5e8c12584872(NewLanguageMTM.structure)/6070516705893290488");
    b.version(3);
    b.property("description", 0x543ecec7f1d811fcL).type(PrimitiveTypeId.STRING).origin("6070516705893290492").done();
    b.property("value", 0x543ecec7f1dc63deL).type(PrimitiveTypeId.STRING).origin("6070516705893573598").done();
    b.aggregate("dataFlowInstance", 0x623cd6c3607a7c8bL).target(0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x623cd6c36070995bL).optional(true).ordered(true).multiple(true).origin("7078768848945183883").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDataFlowInstance() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguageMTM", "DataFlowInstance", 0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x623cd6c36070995bL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:6c0627d3-4986-4ace-b681-5e8c12584872(NewLanguageMTM.structure)/7078768848944535899");
    b.version(3);
    b.aggregate("dataFlow", 0x623cd6c36070995dL).target(0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x543ecec7f1d811f8L).optional(false).ordered(true).multiple(false).origin("7078768848944535901").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDataFlowReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguageMTM", "DataFlowReference", 0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x623cd6c36082c0f0L);
    b.class_(false, false, false);
    b.origin("r:6c0627d3-4986-4ace-b681-5e8c12584872(NewLanguageMTM.structure)/7078768848945725680");
    b.version(3);
    b.associate("dataFlowRef", 0x623cd6c36082c0f1L).target(0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x623cd6c36070995bL).optional(false).origin("7078768848945725681").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDataStore() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguageMTM", "DataStore", 0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x543ecec7f1d811f6L);
    b.class_(false, false, false);
    // extends: NewLanguageMTM.structure.Element
    b.super_(0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x543ecec7f1d7bcd3L);
    b.origin("r:6c0627d3-4986-4ace-b681-5e8c12584872(NewLanguageMTM.structure)/6070516705893290486");
    b.version(3);
    b.alias("store");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguageMTM", "Element", 0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x543ecec7f1d7bcd3L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:6c0627d3-4986-4ace-b681-5e8c12584872(NewLanguageMTM.structure)/6070516705893268691");
    b.version(3);
    b.property("value", 0x543ecec7f1dee31fL).type(PrimitiveTypeId.STRING).origin("6070516705893737247").done();
    b.aggregate("elementInstance", 0x3ced3674405ff198L).target(0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x3ced3674405ff18eL).optional(true).ordered(true).multiple(true).origin("4390225084680237464").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForElementInstance() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguageMTM", "ElementInstance", 0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x3ced3674405ff18eL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:6c0627d3-4986-4ace-b681-5e8c12584872(NewLanguageMTM.structure)/4390225084680237454");
    b.version(3);
    b.property("numberOfElement", 0x2b94098384005db2L).type(PrimitiveTypeId.STRING).origin("3140145300644060594").done();
    b.aggregate("type", 0x5cb095e2345a9113L).target(0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x543ecec7f1d7bcd3L).optional(false).ordered(true).multiple(false).origin("6679003046163943699").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForElementReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguageMTM", "ElementReference", 0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x3ced3674405df3cdL);
    b.class_(false, false, false);
    b.origin("r:6c0627d3-4986-4ace-b681-5e8c12584872(NewLanguageMTM.structure)/4390225084680106957");
    b.version(3);
    b.associate("elementRef", 0x3ced3674405ff191L).target(0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x3ced3674405ff18eL).optional(false).origin("4390225084680237457").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForExternalEntity() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguageMTM", "ExternalEntity", 0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x543ecec7f1d811f4L);
    b.class_(false, false, false);
    // extends: NewLanguageMTM.structure.Element
    b.super_(0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x543ecec7f1d7bcd3L);
    b.origin("r:6c0627d3-4986-4ace-b681-5e8c12584872(NewLanguageMTM.structure)/6070516705893290484");
    b.version(3);
    b.alias("external entity");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFlow() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguageMTM", "Flow", 0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x543ecec7f1d811ffL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:6c0627d3-4986-4ace-b681-5e8c12584872(NewLanguageMTM.structure)/6070516705893290495");
    b.version(3);
    b.associate("input", 0x7b3cd253804cce15L).target(0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x3ced3674405ff18eL).optional(false).origin("8880203821344411157").done();
    b.associate("output", 0x7b3cd253804cce17L).target(0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x3ced3674405ff18eL).optional(false).origin("8880203821344411159").done();
    b.aggregate("inputFlow", 0x235fc52fbdbc757eL).target(0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x543ecec7f1d811f8L).optional(false).ordered(true).multiple(false).origin("2548972722952369534").done();
    b.aggregate("outputFlow", 0x235fc52fbdbc7584L).target(0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x543ecec7f1d811f8L).optional(true).ordered(true).multiple(false).origin("2548972722952369540").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFlowsRepo() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguageMTM", "FlowsRepo", 0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x543ecec7f1d81203L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:6c0627d3-4986-4ace-b681-5e8c12584872(NewLanguageMTM.structure)/6070516705893290499");
    b.version(3);
    b.aggregate("elements", 0x7b3cd253805b75a9L).target(0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x3ced3674405ff18eL).optional(true).ordered(true).multiple(true).origin("8880203821345371561").done();
    b.aggregate("processes", 0x7b3cd25380499495L).target(0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x543ecec7f1d811efL).optional(true).ordered(true).multiple(true).origin("8880203821344199829").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForProcess() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguageMTM", "Process", 0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x543ecec7f1d811efL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:6c0627d3-4986-4ace-b681-5e8c12584872(NewLanguageMTM.structure)/6070516705893290479");
    b.version(3);
    b.property("numeration", 0x543ecec7f1d811f1L).type(PrimitiveTypeId.STRING).origin("6070516705893290481").done();
    b.property("state", 0x13171d15a8271e1L).type(PrimitiveTypeId.STRING).origin("85975011877351905").done();
    b.aggregate("flows", 0x7b3cd253804ccdc1L).target(0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x543ecec7f1d811ffL).optional(true).ordered(true).multiple(true).origin("8880203821344411073").done();
    b.aggregate("subprocesses", 0x13171d15a2f3449L).target(0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x13171d15a3adad2L).optional(true).ordered(true).multiple(true).origin("85975011871896649").done();
    b.alias("process");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSubProcess() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguageMTM", "SubProcess", 0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x13171d15a3adad2L);
    b.class_(false, false, false);
    // extends: NewLanguageMTM.structure.Process
    b.super_(0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x543ecec7f1d811efL);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:6c0627d3-4986-4ace-b681-5e8c12584872(NewLanguageMTM.structure)/85975011872660178");
    b.version(3);
    b.property("nadproces", 0x13171d15a3adad6L).type(PrimitiveTypeId.STRING).origin("85975011872660182").done();
    b.aggregate("flow", 0x623cd6c360763f2eL).target(0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x623cd6c360709960L).optional(false).ordered(true).multiple(false).origin("7078768848944906030").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSubProcessFlow() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("NewLanguageMTM", "SubProcessFlow", 0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x623cd6c360709960L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:6c0627d3-4986-4ace-b681-5e8c12584872(NewLanguageMTM.structure)/7078768848944535904");
    b.version(3);
    b.associate("dataFlowIn", 0x623cd6c360709963L).target(0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x543ecec7f1d811f8L).optional(true).origin("7078768848944535907").done();
    b.associate("dataFlowOut", 0x623cd6c360709965L).target(0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x543ecec7f1d811f8L).optional(true).origin("7078768848944535909").done();
    b.associate("inputFlow", 0x623cd6c360709968L).target(0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x3ced3674405ff18eL).optional(false).origin("7078768848944535912").done();
    b.associate("outputFlow", 0x623cd6c36070996cL).target(0x5dd044a51cd347bbL, 0xa3f5d83db0ac7aebL, 0x3ced3674405ff18eL).optional(false).origin("7078768848944535916").done();
    return b.create();
  }
}
