package NewLanguageMTM.actions;

/*Generated by MPS */

import jetbrains.mps.actions.descriptor.BaseActionAspectDescriptor;
import jetbrains.mps.openapi.actions.descriptor.ActionAspectDescriptor;
import java.util.Collection;
import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;

public class ActionAspectDescriptorImpl extends BaseActionAspectDescriptor implements ActionAspectDescriptor {
  private static final String LANGUAGE_FQ_NAME = "NewLanguageMTM";

  @Override
  public Collection<NodeFactory> getFactories(SAbstractConcept concept) {
    if (LANGUAGE_FQ_NAME.equals(concept.getLanguage().getQualifiedName())) {
      switch (concept.getName()) {
        case "ElementInstance":
          return Collections.<NodeFactory>singletonList(new nodeElementInstanceAddition.NodeFactory_7444934676467951346());
        case "Flow":
          return Collections.<NodeFactory>singletonList(new nodeFactorFlow.NodeFactory_6367742724885409776());
        case "Process":
          return Collections.<NodeFactory>singletonList(new nodeFactorProcess.NodeFactory_2548972722952699592());
        case "SubProcess":
          return Collections.<NodeFactory>singletonList(new nodeSubProcess.NodeFactory_85975011875360413());
        default:
      }
    }
    return Collections.<NodeFactory>emptyList();
  }

}
